### ISSUE TITLE
Dealing with noise data: illegal codons

### ISSUE THREAD

**Issue by nekrut** [davebx/kc-align#4]
Running `kc-align` with the following command:

`kc-align -r ncov.fa -S current_complete_ncov_genomes.fasta -s 26245 -e 26472 --mode genome -p`

eventually fails with the message below. It appears that one of the codons (`SUP`) cannot be translated. It would be nice if `kc-align` errors properly and excludes such sequences from the analysis.

```
nthread = 0
nthreadpair = 0
nthreadtb = 0
ppenalty_ex = 0
stacksize: 8192 kb
rescale = 1
Gap Penalty = -1.53, +0.00, +0.00



Making a distance matrix ..

There are 1 ambiguous characters.
    1 / 2
done.

Constructing a UPGMA tree (efffree=1) ... 
    0 / 2
done.

Progressive alignment 1/1... 
STEP     1 / 1  f
done.

disttbfast (aa) Version 7.467
alg=A, model=BLOSUM62, 1.53, -0.00, -0.00, noshift, amax=0.0
0 thread(s)


Strategy:
 FFT-NS-1 (Very fast but very rough)
 Progressive method (rough guide tree was used.)

If unsure which option to use, try 'mafft --auto input > output'.
For more information, see 'mafft --help', 'mafft --man' and the mafft page.

The default gap scoring scheme has been changed in version 7.110 (2013 Oct).
It tends to insert more gaps into gap-rich regions than previous versions.
To disable this change, add the --leavegappyregion option.

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/anton/anaconda3/envs/kcalign/lib/python3.8/site-packages/Bio/Data/CodonTable.py", line 422, in __getitem__
    possible = list_possible_proteins(codon,
  File "/home/anton/anaconda3/envs/kcalign/lib/python3.8/site-packages/Bio/Data/CodonTable.py", line 241, in list_possible_proteins
    x3 = ambiguous_nucleotide_values[c3]
KeyError: 'P'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anton/anaconda3/envs/kcalign/lib/python3.8/site-packages/Bio/Seq.py", line 2870, in _translate_str
    amino_acids.append(forward_table[codon])
  File "/home/anton/anaconda3/envs/kcalign/lib/python3.8/site-packages/Bio/Data/CodonTable.py", line 427, in __getitem__
    raise KeyError(codon)  # stop codon
KeyError: 'SUP'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anton/anaconda3/envs/kcalign/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/anton/anaconda3/envs/kcalign/lib/python3.8/site-packages/kcalign/__init__.py", line 215, in test_frames
    trans0 = seq2[frame:].translate(stop_symbol='')
  File "/home/anton/anaconda3/envs/kcalign/lib/python3.8/site-packages/Bio/Seq.py", line 1277, in translate
    protein = _translate_str(
  File "/home/anton/anaconda3/envs/kcalign/lib/python3.8/site-packages/Bio/Seq.py", line 2887, in _translate_str
    raise CodonTable.TranslationError(
Bio.Data.CodonTable.TranslationError: Codon 'SUP' is invalid
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anton/anaconda3/envs/kcalign/bin/kc-align", line 11, in <module>
    sys.exit(main())
  File "/home/anton/anaconda3/envs/kcalign/lib/python3.8/site-packages/kcalign/cli.py", line 19, in main
    genome_mode(args.reference, args.seqs, args.start, args.end, args.compress, args.para)
  File "/home/anton/anaconda3/envs/kcalign/lib/python3.8/site-packages/kcalign/__init__.py", line 523, in genome_mode
    seqs, names, ids, og_seqs, err = create_lists(reads, seq, og_seqs, join, para)
  File "/home/anton/anaconda3/envs/kcalign/lib/python3.8/site-packages/kcalign/__init__.py", line 378, in create_lists
    result = para_find_homologs(seq, record.seq)
  File "/home/anton/anaconda3/envs/kcalign/lib/python3.8/site-packages/kcalign/__init__.py", line 163, in para_find_homologs
    if res.result() == 1:
  File "/home/anton/anaconda3/envs/kcalign/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/anton/anaconda3/envs/kcalign/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
Bio.Data.CodonTable.TranslationError: Codon 'SUP' is invalid
```

**Comment by nickeener** [comment]
Solved with this commit: https://github.com/davebx/kc-align/commit/fd4af1a17cfc9ffbe1c38ec7f1b371bc995b96d3. Kc-Align will now scan inputs for illegal characters before proceeding to alignment.
